---
engines:
  eslint:
    enabled: true
    checks:
      no-extend-native:
        enabled: false
      no-eq-null:
        enabled: false
      # Disable eqeqeq for no warning on combo undefined and null check
      eqeqeq:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - src/**/*.js
exclude_paths:
  - test/**/*

